// 建档与设置共用的字段定义，校验范围与输入控件保持一致。
export const numericSettingFields = {
  height: { label: "身高 (cm)", min: 120, max: 230, placeholder: "178", required: "请填写身高", message: "请输入 120–230cm" },
  age: { label: "年龄", min: 18, max: 100, placeholder: "34", required: "请填写年龄", message: "请输入 18–100 岁" },
  weight: {
    label: "当前体重 (kg)",
    min: 40,
    max: 200,
    step: 0.1,
    placeholder: "86.4",
    required: "请填写当前体重",
    message: "请输入 40–200kg",
  },
  targetWeight: {
    label: "目标体重 (kg)",
    min: 40,
    max: 180,
    step: 0.1,
    placeholder: "76",
    required: "请填写目标体重",
    message: "请输入 40–180kg",
  },
  weeklyLoss: {
    label: "每周减重目标 (kg/周)",
    min: 0.1,
    max: 1.2,
    step: 0.1,
    required: "请填写每周减重目标",
    message: "每周减重目标请输入 0.1–1.2 kg/周",
  },
  calories: {
    label: "每日热量预算 (kcal)",
    min: 1200,
    max: 3600,
    step: 1,
    placeholder: "1880",
    required: "请填写每日热量预算，或使用估算值",
    message: "请输入 1200–3600 kcal",
  },
  waist: {
    label: "当前腰围 (cm)",
    min: 50,
    max: 180,
    step: 0.1,
    placeholder: "96",
    optional: true,
    message: "请输入 50–180cm",
  },
  targetWaist: {
    label: "目标腰围 (cm)",
    min: 50,
    max: 160,
    step: 0.1,
    placeholder: "86",
    optional: true,
    message: "请输入 50–160cm",
  },
};
